[package]
name = "testpr"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.12.0"
time = { version = "0.3.41", features = ["macros"] }
rand = "0.9.1"
